[project]
name = "datagen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
main = "datagen.main:main"

# ---------------------------------------------
# Build backend for packaging
# ---------------------------------------------
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
