name: '[tst]: documentation deploy'

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: tst

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/uv-setup

      - name: mkdocs build
        run: uv run mkdocs build --site-dir build/docs/

      - name: dbt docs generate
        run: |
          uv run dbt docs generate \
            --project-dir dbt/sample_project \
            --profiles-dir .dbt/workflows \
            --target cicd

          mv dbt/sample_project/target build/docs/dbt
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

          DBT_CATALOG: ${{ vars.DBT_CATALOG }}
          DBT_SCHEMA: ${{ vars.DBT_SCHEMA }}
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_HTTP_PATH: ${{ vars.DATABRICKS_HTTP_PATH }}

      - name: upload pages (artifact)
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: tst
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
