name: 'validation (pr title) - Conventional Commits'

permissions:
  pull-requests: read
  statuses: write

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    name: '[validate]: pr name'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:

          # feat(ui): Add `Button` component
          #  ^    ^    ^
          #  |    |    |__ Subject
          #  |    |_______ Scope
          #  |____________ Type

          types: |
            feat
            fix
            perf
            refactor
            build
            ci
            docs
            test
            style
            chore
            revert
          requireScope: false
          subjectPattern: ^[a-zA-Z0-9 ,_./-]+(\[ADR-[0-9]+\])?
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Any letters or numbers and spaces
            followed by an optional Jira ticket number in square brackets is allowed.

          # For work-in-progress PRs you can typically use draft pull requests from GitHub.
          # However, private repositories on the free plan don't have this option and therefore this action allows you to opt-in to using the special "[WIP]" prefix to indicate this state.

          # example:
          # [WIP] feat: Add support for Node.js 18
          wip: true
