name: Validate PR title

permissions:
  pull-requests: read
  statuses: write

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths-ignore:
      - configuration/**
  workflow_dispatch:

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            improvement
            docs
            refactor
            test
            ci
            chore
            hotfix
            revert
          requireScope: false
          subjectPattern: ^[a-zA-Z0-9 ,_./-]+(\[DDP-[0-9]+\])?
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Any letters or numbers and spaces
            followed by an optional Jira ticket number in square brackets is allowed.
          wip: true
